services:
  composer_update:
    image: composer:2.8
    user: ${MY_UID}:${MY_GID}
    volumes:
      - type: bind
        source: ./src
        target: /app
    command: composer install

  php:
    image: php:8.3-apache
    environment:
      - DEBUG=${DEBUG}
      - BASE_PATH=/
    volumes:
      - type: bind
        source: ./src
        target: /var/www/html
    ports:
      - "8000:80"
    depends_on:
      composer_update:
        condition: service_completed_successfully
    restart: unless-stopped
