name: Build & Deploy

on:
  push:
    branch: main

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Clone
      uses: actions/checkout@v5
      with:
        submodules: true

    - name: Install dependencies
      run: |
        sudo apt-get update && 
        sudo apt-get install -y lftp

    - name: Set known hosts
      env:
        KNOWN_HOSTS: ${{secrets.known_hosts}}
      run: echo "$KNOWN_HOSTS" > ~/.ssh/known_hosts

    - name: Upload
      env:
        SFTP_HOST: ${{secrets.sftp_host}}
        SFTP_USER: ${{secrets.sftp_user}}
        LFTP_PASSWORD: ${{secrets.sftp_pass}}
      run: |
        lftp <<EOT
        set cmd:fail-exit true
        set cmd:interactive false
        set net:timeout 10
        open -u $SFTP_USER --env-password sftp://$SFTP_HOST
        lcd src
        mirror --reverse --delete --verbose=3
        exit
        EOT

