name: Build & Deploy

on:
  push:

permissions:
  contents: read

jobs:
  prep:
    runs-on: ubuntu-latest

    steps:
    - name: Clone
      uses: actions/checkout@v5
      with:
        submodules: true

    - name: Install SFTP
      run: sudo apt-get install -y sftp