name: Build & Deploy

on:
  push:
    branch: main

jobs:
  deploy:
    environment: prod
    runs-on: ubuntu-latest

    steps:
    - name: Clone
      uses: actions/checkout@v5

    - name: Install Composer packages
      uses: docker://composer:2.8
      with: 
        args: env -C src composer install

    # Composer container runs as root, so need to chown.
    - name: chown vendor directory
      run: sudo chown -R $USER:$USER src/vendor

    - name: Delete un-needed files
      run: >
        rm -rf
        src/composer.*
        src/vendor/*/*/{composer.json,LICENSE,*.md}
        src/vendor/smarty/smarty/{changelog,demo,docs,Makefile,mkdocs.yml,*.sh,TODO.txt}

    - name: Install tools
      # We remove some un-needed DPKG triggers to speed up install process.
      run: |
        sudo apt-get update && 
        sudo sed -i -e '/man-db/ d' -e '/icon-theme/ d' /var/lib/dpkg/triggers/File &&
        sudo apt-get install -y lftp

    - name: Set known hosts
      env:
        KNOWN_HOSTS: ${{secrets.known_hosts}}
      run: |
        mkdir -p ~/.ssh &&
        echo "$KNOWN_HOSTS" > ~/.ssh/known_hosts

    - name: Upload
      env:
        SFTP_HOST: ${{secrets.sftp_host}}
        SFTP_USER: ${{secrets.sftp_user}}
        LFTP_PASSWORD: ${{secrets.sftp_pass}}
      run: |
        lftp <<EOT
        set cmd:fail-exit true
        set cmd:interactive false
        set net:timeout 10
        open -u $SFTP_USER --env-password sftp://$SFTP_HOST
        mirror --reverse --delete --verbose=3 --parallel=10 src /
        exit
        EOT

