name: Build & Deploy

on:
  push:
    branch: main

jobs:
  deploy:
    environment: prod
    runs-on: ubuntu-latest

    steps:
    - name: Clone
      uses: actions/checkout@v5

    - name: Install Composer packages
      run: |
        docker run --rm --volume ./src:/app --user "$(id -u)" composer:2.8 composer install

    - name: Template config files
      env:
        LOGFILE: ${{secrets.logpath}}
        RTT_USER: ${{secrets.rtt_user}}
        RTT_PASS: ${{secrets.rtt_pass}}
      run: |
        m4 --prefix-builtins \
          --define=RTT_USERNAME_VALUE="$RTT_USER" \
          --define=RTT_PASSWORD_VALUE="$RTT_PASS" \
          src/config/creds.php.m4 > src/config/creds.php
        m4 --prefix-builtins --define=LOGPATH="$LOGPATH" src/php.ini.m4 > src/php.ini

    - name: Delete un-needed files
      run: |
        shopt -s globstar
        rm -rf \
          src/**/*.m4 \
          src/composer.* \
          src/vendor/*/*/{composer.json,LICENSE,*.md} \
          src/vendor/smarty/smarty/{changelog,demo,docs,Makefile,mkdocs.yml,*.sh,TODO.txt}

    - name: Install tools
      # We only include bare minimum repos to speet up apt-get update.
      # We remove some un-needed DPKG triggers to speed up apt-get install.
      run: |
        set -e
        sudo rm -f /etc/apt/sources.list /etc/apt/sources.list.d/*.list
        for repo in jammy{,-updates,-security}; do
          echo deb http://archive.ubuntu.com/ubuntu/ "$repo" main | sudo tee -a /etc/apt/sources.list
        done
        sudo apt-get update
        sudo sed -i -e '/man-db/ d' -e '/icon-theme/ d' /var/lib/dpkg/triggers/File
        sudo apt-get install -y lftp

    - name: Set known hosts
      env:
        KNOWN_HOSTS: ${{secrets.known_hosts}}
      run: |
        mkdir -p ~/.ssh &&
        echo "$KNOWN_HOSTS" > ~/.ssh/known_hosts

    - name: Upload
      env:
        SFTP_HOST: ${{secrets.sftp_host}}
        SFTP_USER: ${{secrets.sftp_user}}
        LFTP_PASSWORD: ${{secrets.sftp_pass}}
      run: |
        lftp <<EOT
        set cmd:fail-exit true
        set cmd:interactive false
        set net:timeout 10
        open -u $SFTP_USER --env-password sftp://$SFTP_HOST
        mirror --reverse --delete --verbose=3 --parallel=10 src /
        exit
        EOT

